name: Android CI

on: [push, pull_request]

jobs:
  permission:
    name: gradle executable permission
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      
      - name: Make Gradle executable
        uses: actions/checkout@v2
        run: chmod +x ./gradlew

  lint:
    name: Spotless check
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: spotless
        run: ./gradlew spotlessCheck

  api_check:
    name: API check
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: API check
        run: ./gradlew apiCheck

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Cache Gradle and wrapper
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
           ${{ runner.os }}-gradle-
      
    - name: Build with Gradle
      run: ./gradlew build
